# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
State.create([
{stcode: 'Select state', state: ''},
{stcode: 'Alabama', state: 'AL'},
{stcode: 'Alaska', state: 'AK'},
{stcode: 'Arizona', state: 'AZ'},
{stcode: 'Arkansas', state: 'AR'},
{stcode: 'California', state: 'CA'},
{stcode: 'Colorado', state: 'CO'},
{stcode: 'Connecticut', state: 'CT'},
{stcode: 'Delaware', state: 'DE'},
{stcode: 'Florida', state: 'FL'},
{stcode: 'Georgia', state: 'GA'},
{stcode: 'Guam', state: 'GU'},
{stcode: 'Hawaii', state: 'HI'},
{stcode: 'Idaho', state: 'ID'},
{stcode: 'Illinois', state: 'IL'},
{stcode: 'Indiana', state: 'IN'},
{stcode: 'Iowa', state: 'IA'},
{stcode: 'Kansas', state: 'KS'},
{stcode: 'Kentucky', state: 'KY'},
{stcode: 'Louisiana', state: 'LA'},
{stcode: 'Maine', state: 'ME'},
{stcode: 'Maryland', state: 'MD'},
{stcode: 'Michigan', state: 'MI'},
{stcode: 'Minnesota', state: 'MN'},
{stcode: 'Mississippi', state: 'MS'},
{stcode: 'Missouri', state: 'MO'},
{stcode: 'Montana', state: 'MT'},
{stcode: 'Nebraska', state: 'NE'},
{stcode: 'Nevada', state: 'NV'},
{stcode: 'New Hampshire', state: 'NH'},
{stcode: 'New Jersey', state: 'NJ'},
{stcode: 'New Mexico', state: 'NM'},
{stcode: 'New York', state: 'NY'},
{stcode: 'North Carolina', state: 'NC'},
{stcode: 'North Dakota', state: 'ND'},
{stcode: 'Ohio', state: 'OH'},
{stcode: 'Oklahoma', state: 'OK'},
{stcode: 'Oregon', state: 'OR'},
{stcode: 'Pennsylvania', state: 'PA'},
{stcode: 'Rhode Island', state: 'RI'},
{stcode: 'South Carolina', state: 'SC'},
{stcode: 'Tennessee', state: 'TN'},
{stcode: 'Texas', state: 'TX'},
{stcode: 'Utah', state: 'UT'},
{stcode: 'Vermont', state: 'VT'},
{stcode: 'Virginia', state: 'VA'},
{stcode: 'Virgin Islands', state: 'VI'},
{stcode: 'Washington', state: 'WA'},
{stcode: 'West Virginia', state: 'WV'},
{stcode: 'Wisconsin', state: 'WI'},
{stcode: 'Wyoming', state: 'WY'}
])
